CREATE TABLE PROFILE (
	PRO_ID INT PRIMARY KEY,
	PRO_NAME VARCHAR(15),
	PRO_SURNAME VARCHAR(15),
	PRO_DESC VARCHAR(50),
	PRO_IMG VARCHAR(100)
);

CREATE TABLE STUDY_TYPE (
	STY_ID INT PRIMARY KEY,
	STY_NAME VARCHAR(15)
);

CREATE TABLE STUDIES (
	STD_ID INT PRIMARY KEY,
	STD_STY_ID INT,
	CONSTRAINT FK_STD_STY_ID FOREIGN KEY (STD_STY_ID) REFERENCES STUDY_TYPE(STY_ID),
	STD_TITLE VARCHAR(30),
	STD_DESCRIPTION VARCHAR(500),
	STD_INTITUTION VARCHAR(50),
	STD_START_DATE DATE,
	STD_END_DATE DATE,
	STD_HOURS INT,
	STD_CERTIFICATION_URL VARCHAR(100)
);

CREATE TABLE ASSIGNATURES(
	ASG_ID INT PRIMARY KEY,
	ASG_STD_ID INT,
	CONSTRAINT FK_ASG_STD_ID FOREIGN KEY (ASG_STD_ID) REFERENCES STUDIES(STD_ID),
	ASG_TITLE VARCHAR(30),
	ASG_FIRST_NOTE FLOAT,
	ASG_SECOND_NOTE FLOAT,
	ASG_PROMOTION BIT,
	ASG_SEMESTER INT,
	ASG_STATUS VARCHAR(20)
);

CREATE TABLE TECH_TYPES(
	TCY_ID INT PRIMARY KEY,
	TCY_NAME VARCHAR(30)
);

CREATE TABLE TECHNOLOGIES(
	TEC_ID INT PRIMARY KEY,
	TEC_TCY_ID INT,
	CONSTRAINT FK_TEC_TCY_ID FOREIGN KEY (TEC_TCY_ID) REFERENCES TECH_TYPES(TCY_ID),

);

CREATE TABLE PROJECTS(
	PRO_ID INT PRIMARY KEY,
	PRO_TITLE VARCHAR(50),
	PRO_IMG_1 VARCHAR(100),
	PRO_IMG_2 VARCHAR(100),
	PRO_IMG_3 VARCHAR(100),
	PRO_IMG_4 VARCHAR(100),
	PRO_DESCRIPTION VARCHAR(500),
	PRO_GITHUB_URL VARCHAR(100),
	PRO_PRODUCTION_URL VARCHAR(100)
);

CREATE TABLE PROJECT_TECHNOLOGIES(
	PRT_ID INT PRIMARY KEY,
	PRT_PRO_ID INT,
	CONSTRAINT FK_PRT_PRO_ID FOREIGN KEY (PRT_PRO_ID) REFERENCES PROJECTS(PRO_ID),
	PRT_TEC_ID INT,
	CONSTRAINT FK_PRT_TEC_ID FOREIGN KEY (PRT_TEC_ID) REFERENCES TECHNOLOGIES(TEC_ID)
);